server.port=8080

# Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-restless-resonance-adrph0bo-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_RLHIN4MAQ1gY

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
