spring.datasource.url=jdbc:postgresql://ep-lively-block-a7t0tkvg-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_DJANE5FMkG0v

resend.api-key=re_V96mCwJM_K2VSYifoy9dq2u4AK2YRrLff
resend.from-email=onboarding@resend.dev

GOOGLE_CLIENT_ID=492060445279-62qlapkte01fmn8urbabp9n89u9f4qod.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=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
GOOGLE_REDIRECT_URI=http://localhost:8080/api/drive/callback

anthropic.api-key=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